version: "3.8"

volumes:
  grafana_data:
  prometheus_data:
  mysql_data:

networks:
  monitoring:
    external: true

services:

  grafana:
    image: grafana/grafana:9.1.6
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
    ports:
      - 3000:3000
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: always
    volumes:
      -  prometheus_data:/prometheus
      -  D:\cadastro_funcionario\cadastro_funcionario\web\src\main\resources\grafana-prometheus\prometheus\:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=360h'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring

  java:
    image: damariscollopy/java:v1
    container_name: java
    restart: always
    environment:
      - 'spring.datasource.username=root'
      - 'spring.datasource.password=pensealem'
      - 'spring.datasource.url=jdbc:mysql://mysql:3306/gestao_empresa?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=GMT'
      - 'spring.jpa.hibernate.ddl-auto=update'
      - 'management.metrics.enable.jvm=true'
      - 'management.endpoints.web.exposure.include=*'
      - 'management.endpoint.health.enabled=true'
      - 'managment.endpoints.enabled-by-default=false'
      - 'management.endpoint.info.enabled=true'
      - 'management.endpoint.prometheus.enabled=true'
      - 'management.endpoint.metrics.enabled=true'
      - 'management.endpoint.health.show-details=always'
    ports:
      - 8080:8080
    networks:
     - monitoring

  mysql:
    image: mysql:8.0.26
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3307:3307
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitoring

